import type { Activity, FamilyMember } from '@/domain/types';

export const WILIAN = 'wilian';
export const ANA = 'ana';
export const NICOLAS = 'nicolas';
/** Tarefas que sao da casa e nao de uma pessoa (ex.: missoes de zona). */
export const SHARED = 'familia';

export const FAMILY: FamilyMember[] = [
  {
    id: WILIAN,
    name: 'Wilian',
    color: 'wilian',
    isChild: false,
    work: {
      label: 'Home office',
      days: [1, 2, 3, 4, 5],
      start: '09:00',
      end: '18:00',
      homeOffice: true,
    },
    responsibilities: [
      'Preparar o Nicolas de manhã',
      'Ajudar o Nicolas a vestir-se',
      'Pequeno-almoço',
      'Verificar a mochila',
      'Levar o Nicolas à escola',
      'Buscar o Nicolas',
      'Buscar a Ana',
      'Levar o Nicolas às atividades',
      'Acompanhar o banho',
      'Acompanhar a rotina do Nicolas',
      'Logística familiar',
      'Roupa das atividades',
    ],
  },
  {
    id: ANA,
    name: 'Ana',
    color: 'ana',
    isChild: false,
    work: {
      label: 'Trabalho fora',
      days: [1, 2, 3, 4, 5],
      start: '08:00',
      end: '17:00',
      homeOffice: false,
    },
    responsibilities: [
      'Refeições',
      'Preparação e base do jantar',
      'Verificar alimentos para o dia seguinte',
      'Descongelar alimentos quando necessário',
      'Tarefas curtas nos dias de atividade',
      'Apoio à roupa',
      'Dobragem',
      'Fechar a cozinha quando o Wilian estiver nas atividades',
    ],
  },
  {
    id: NICOLAS,
    name: 'Nicolas',
    color: 'nicolas',
    isChild: true,
    responsibilities: [
      'Ajudar a arrumar a cama',
      'Pijama no lugar',
      'Roupa suja no cesto',
      'Guardar brinquedos',
      'Levar prato e copo para a cozinha',
      'Organizar a mochila',
      'Organizar os sapatos',
      'Organizar o quarto',
      'Guardar meias, cuecas e pijamas',
      'Guardar as toalhas pequenas',
    ],
  },
];

export const ACTIVITIES: Activity[] = [
  {
    id: 'escola-seg',
    title: 'Escola',
    icon: '🎒',
    day: 1,
    start: '09:00',
    end: '17:00',
    memberId: NICOLAS,
    external: false,
  },
  {
    id: 'escola-ter',
    title: 'Escola',
    icon: '🎒',
    day: 2,
    start: '09:00',
    end: '17:00',
    memberId: NICOLAS,
    external: false,
  },
  {
    id: 'escola-qua',
    title: 'Escola',
    icon: '🎒',
    day: 3,
    start: '09:00',
    end: '17:00',
    memberId: NICOLAS,
    external: false,
  },
  {
    id: 'escola-qui',
    title: 'Escola',
    icon: '🎒',
    day: 4,
    start: '09:00',
    end: '17:00',
    memberId: NICOLAS,
    external: false,
  },
  {
    id: 'escola-sex',
    title: 'Escola',
    icon: '🎒',
    day: 5,
    start: '09:00',
    end: '17:00',
    memberId: NICOLAS,
    external: false,
  },
  {
    id: 'natacao',
    title: 'Natação',
    icon: '🏊',
    day: 1,
    start: '18:00',
    end: '19:00',
    memberId: NICOLAS,
    escortId: WILIAN,
    external: true,
  },
  {
    id: 'jiujitsu-qua',
    title: 'Jiu-jitsu',
    icon: '🥋',
    day: 3,
    start: '18:30',
    end: '19:30',
    memberId: NICOLAS,
    escortId: WILIAN,
    external: true,
  },
  {
    id: 'jiujitsu-sex',
    title: 'Jiu-jitsu',
    icon: '🥋',
    day: 5,
    start: '18:30',
    end: '19:30',
    memberId: NICOLAS,
    escortId: WILIAN,
    external: true,
  },
];
